# Generated by Django 4.0.4 on 2022-07-04 22:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0003_post_delete_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_meta',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
