# Generated by Django 4.0.4 on 2022-07-11 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0004_alter_post_blog_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug_post',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
