# Generated by Django 4.0.4 on 2022-07-12 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0005_post_slug_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30, unique=True)),
                ('psw', models.CharField(max_length=30)),
                ('date_creation', models.DateField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='topic_tag',
        ),
        migrations.AddField(
            model_name='post',
            name='topic_tag',
            field=models.ManyToManyField(to='my_blog.topics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_blog.usermodel'),
        ),
    ]
