# Generated by Django 4.0.4 on 2022-07-12 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0006_topics_usermodel_remove_post_topic_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='date_creation',
        ),
    ]
