# Generated by Django 4.0.4 on 2022-07-12 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0007_remove_usermodel_date_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_name',
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
