# Generated by Django 4.0.4 on 2022-07-20 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0018_alter_comments_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='body',
            new_name='comment',
        ),
    ]
